---
- name: Create VM
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    vm_base_name: "testvm"

  tasks:
    - name: Generate random identifier
      set_fact:
        random_id: "{{ lookup('community.general.random_string', upper=false, numbers=false, special=false, length=4) }}"

    - name: Set VM name
      set_fact:
        vm_name: "{{ vm_base_name }}-{{ random_id }}"

    - name: Create VM
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ vm_name }}"
        namespace: default
        labels:
          app: test
        instancetype:
          name: u1.medium
        preference:
          name: rhel.9
        data_volume_templates:
          - metadata:
              name: "rhel-9-{{ vm_name }}-volume"
            spec:
              sourceRef:
                kind: DataSource
                name: rhel9
                namespace: openshift-virtualization-os-images
              storage:
                resources: {}
        spec:
          accessCredentials:
            - sshPublicKey:
                propagationMethod:
                  qemuGuestAgent:
                    users:
                      - cloud-user
                source:
                  secret:
                    secretName: ssh-key
          domain:
            devices: {}
            machine:
              type: pc-q35-rhel9.4.0
          volumes:
            - dataVolume:
                name: "rhel-9-{{ vm_name }}-volume"
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  chpasswd:
                    expire: false
                  password: password
                  user: cloud-user
                  runcmd:
                  - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
              name: cloudinitdisk
        wait: true
        wait_timeout: 600
