---
- name: Create VM
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create a VM
      redhat.openshift_virtualization.kubevirt_vm:
        name: testvm
        namespace: default
        labels:
          app: test
        instancetype:
          name: u1.small
        preference:
          name: centos.stream9
        spec:
          accessCredentials:
            - sshPublicKey:
                propagationMethod:
                  noCloud: {}
                source:
                  secret:
                    secretName: ssh-key
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
          networks:
            - name: default
              pod: {}
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/centos-stream:9
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  chpasswrd:
                    expire: false
                  password: password
                  user: cloud-user
              name: cloudinitdisk
        wait: true
        wait_timeout: 600
